steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - task: Cache@2
    inputs:
      key: 'yarn | "$(Agent.OS)" | yarn.lock'
      restoreKeys: |
        yarn | "$(Agent.OS)"
        yarn
      path: $(Pipeline.Cache)
      cacheHitVar: CACHE_RESTORED
    displayName: Cache dependencies

  - pwsh: |
      yarn config set cache-folder $(Pipeline.Cache)
      yarn --ignore-engines --frozen-lockfile
    displayName: Yarn install
